name: build
on:
  push

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
          architecture: 'x64'

      - name: install dependencies
        shell: bash
        run: |
          pip install --upgrade pip setuptools==60.6.0 wheel
          python -m pip install -r requirements.txt

      - name: build main.py
        shell: bash
        run: |
          python -m nuitka \
            --standalone \
            --plugin-enable=numpy \
            --assume-yes-for-downloads \
            --follow-imports \
            --no-prefer-source-code \
            --follow-import-to=numpy \
            --include-package-data=scipy \
            --include-data-file=${{ env.pythonLocation }}/lib/python*/site-packages/scipy/.dylibs/*.dylib=./scipy/.dylibs/ \
            main.py

      - name: test binary
        shell: bash
        working-directory: main.dist
        run: ./main