name: build
on:
  push

jobs:
  build-macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: install dependencies
        shell: bash
        run: python -m pip install -r requirements.txt

      - name: build main.py
        shell: bash
        run: |
          python -m nuitka \
            --standalone \
            --plugin-enable=numpy \
            --follow-imports \
            --no-prefer-source-code \
            main.py

      - name: test main.exe
        shell: bash
        working-directory: main.dist
        run: ./main.exe